export const styleConstants = {
    INNER_WIDTH_SIZE: 768,
    DRAWER_WIDTH: 240,
    COLLAPSED_WIDTH: 64,
    TRANSITION_DURATION: 0.3,
    TOOLBAR_HEIGHT: 64,
    FONT_SIZE_DEFAULT: '1.0em',
    VERTICAL_ALIGN_DEFAULT: '0.1em',
};  