name: Run Tutorial Tests

on: 
  push:
    branches: 
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        ref: development

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install Dependencies
      run: npm install  

    - name: Run Gulp
      run: gulp

    - name: Run headless test
      uses: GabrielBB/xvfb-action@v1.0
      with:
        run: npm test

