name: PlayWright Test

on: 
  push:
    branches: 
      - 181-playwright

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        ref: 181-playwright

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install Java
      run: /usr/bin/sudo apt-get install openjdk-8-jre-headless

    - name: Install Node Dependencies
      run: npm install  

    - name: Run Gulp
      run: gulp

    - name: Run headless tests
      uses: GabrielBB/xvfb-action@v1.0
      with:
        run: npm test
