name: Release INTO-CPS App

on:
  push:
    branches:
      - development
      - draft-and-graphs
  workflow_dispatch:

jobs:
  release:
    name: Create Draft Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Download Linux artifacts
        uses: actions/download-artifact@v3
        with:
          name: release-ubuntu-latest
          path: ./release/ubuntu

      - name: Download Windows artifacts
        uses: actions/download-artifact@v3
        with:
          name: release-windows-latest
          path: ./release/windows

      - name: Semantic Release (Draft)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx ts-node --esm release.config.ts

      - name: Upload artifacts to Draft Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./release/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
